# Generated by Django 6.0.5 on 2026-05-31 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=100)),
                ('id_anggota', models.CharField(max_length=20, unique=True)),
                ('_email', models.EmailField(db_column='email', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('kategori', models.CharField(blank=True, max_length=50)),
                ('_stok', models.IntegerField(db_column='stok', default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Konfigurasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denda_per_hari', models.IntegerField(default=2000)),
                ('maks_denda', models.IntegerField(default=50000)),
                ('durasi_pinjam', models.IntegerField(default=7)),
                ('maks_buku', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('dipinjam', 'Dipinjam'), ('terlambat', 'Terlambat'), ('kembali', 'Dikembalikan')], default='dipinjam', max_length=20)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('jatuh_tempo', models.DateField()),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.anggota')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
